name: Integration Test CI

on:
  workflow_run:
    workflows: ['Node.js CI Setup']
    branches:
      - develop
    types:
      - completed

jobs:
  nestjs-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install docker-compose
        uses: KengoTODA/actions-setup-docker-compose@v1
        with:
          version: '2.14.2'

      - name: Use Node.js (.nvmrc)
        uses: actions/setup-node@v4
        with:
          node-version: '${{ steps.nvm.outputs.NVMRC }}'
          cache: 'npm'

      - run: npm i

      - run: npm run test:nestjs
